base_url = "https://senyablog.netlify.app/"
description = "blog site build with zola"
compile_sass = false
minify_html = true
generate_feed = true

default_language = "en"

taxonomies = [{ name = "tags", feed = true }]

[languages.en]
weight = 1
title = "Blog"
languageName = "English"
languageCode = "en"
relativeURL = false


[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = true
highlight_theme = "gruvbox-dark"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

[extra]
author = "Speyll"
favicon = "favicon.ico"
image = ""
list_pages = false
twitter_card = true

[[extra.header_nav]]
en = { name = "/home/", url = "/" }


[[extra.header_nav]]
en = { name = "/about/", url = "/about" }


[[extra.header_nav]]
en = { name = "/blog/", url = "/blog" }

[[extra.header_nav]]
en = { name = "/resources/", url = "/resources" }

[server]
interface = "0.0.0.0"
