name: test

on:
  push:
    branches:
      - features 

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.17.1
          
      - name: Run Zola Server
        run: zola serve --interface 127.0.0.1 --port 4000 --root-dir src

      - name: Test Zola Build
        run: |
          sleep 5  # Wait for the server to start
          curl http://127.0.0.1:4000/tests/test.html  # Change URL to match your test page
